name: media_gallery
description: A Flutter plugin that lists native gallery items.
version: 0.1.5
homepage: https://github.com/aloisdeniel/media_gallery

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.media_gallery
        pluginClass: MediaGalleryPlugin
      ios:
        pluginClass: MediaGalleryPlugin
